/* eslint-disable react-hooks/rules-of-hooks */
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import HomeLayout from '../components/layouts/homeLayout'
import { Heading } from '@chakra-ui/react'
import { Form } from '../components/elements/form'
import { useEffect, useState } from 'react'
import { usePixabayDataSWR } from '../hooks/usePixabayDataSWR'
import { fetcher } from '../libs/fetcher'

const Home: NextPage = () => {
  const [url, setUrl] = useState<string>('')
  useEffect(() => {
    console.log(url)
    if (url != '') {
      console.log('gyaaaaaaaaaa')
      // eslint-disable-next-line react-hooks/rules-of-hooks
      // const { data, isLoading, isError } = usePixabayDataSWR(url)
      const { data, error } = useSWR(url, fetcher)
      console.log(data)
    }
  }, [url])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout title="pixabay-app">
        <Heading as="h1">pixabay-app</Heading>
        <Form setUrl={setUrl}></Form>
      </HomeLayout>
    </div>
  )
}

export default Home
function useSWR(
  url: string,
  fetcher: (url: string) => Promise<() => Promise<any>>
): { data: any; error: any } {
  throw new Error('Function not implemented.')
}
